# No build-system here, used for tool configuration only
[tool.mypy]
python_version = "3.13"
files = ["*.py"]
warn_unused_configs = true

strict = true
disallow_untyped_defs = true

enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true

[tool.ruff]
target-version = "py313"
line-length = 100
lint.select = [ "ALL" ]
lint.ignore = [
    "ANN401",  # any-type
    "C901",    # Complexity
    "D",       # Doc
    "S101",    # Use of `assert` detected
    "PD002",   # TODO `inplace=True` should be avoided; it has inconsistent behavior
    "PD010",   # TODO `.pivot_table` is preferred to `.pivot` or `.unstack`; provides same functionality
    "PD011",   # TODO Use `.to_numpy()` instead of `.values`
    "PD013",   # TODO `.melt` is preferred to `.stack`; provides same functionality
    "PLR",     # Design related pylint codes
    "S113",    # TODO Probable use of `requests` call without timeout
]
