# No build-system here, used for tool configuration only

[tool.black]
target-version = ["py313"]

[tool.isort]
profile = "black"

[tool.mypy]
python_version = "3.13"
files = ["*.py"]
warn_unused_configs = true

strict = true
disallow_untyped_defs = true

enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true
